In [1]:
#!pip install openpyxl

In [2]:
import pandas as pd
import openpyxl

Selecionando os dados de malária:

In [3]:
epidem_indic = pd.read_excel('TRAJETORIAS_DATASET_Epidemiological_dimension_indicators.xlsx')

# Define os valores desejados
malaria = ['Falciparum', 'Vivax', 'Vivax+Falciparum']

# Filtra as linhas com os valores desejados na coluna 'disease'
malaria_df = epidem_indic[epidem_indic['disease'].isin(malaria)]

# Exibe as linhas filtradas
malaria_df = malaria_df.reset_index()
malaria_df = malaria_df.drop(['index'], axis=1)
malaria_df

,state_abbrev,state,municipality,geocode,period,zone,disease,cases,inc
0,RO,Rondônia,Alta Floresta D'Oeste,1100015,2004-2008,rural,Falciparum,121,195.271489
1,RO,Rondônia,Alto Alegre dos Parecis,1100379,2004-2008,rural,Falciparum,19,34.407025
2,RO,Rondônia,Alto Paraíso,1100403,2004-2008,rural,Falciparum,5209,12103.864539
3,RO,Rondônia,Alvorada D'Oeste,1100346,2004-2008,rural,Falciparum,159,341.565402
4,RO,Rondônia,Ariquemes,1100023,2004-2008,rural,Falciparum,3106,4669.549141
...,...,...,...,...,...,...,...,...,...
13891,MT,Mato Grosso,Vale de São Domingos,5108352,2015-2019,total,Vivax+Falciparum,0,0.000000
13892,MT,Mato Grosso,Várzea Grande,5108402,2015-2019,total,Vivax+Falciparum,0,0.000000
13893,MT,Mato Grosso,Vera,5108501,2015-2019,total,Vivax+Falciparum,0,0.000000
13894,MT,Mato Grosso,Vila Bela da Santíssima Trindade,5105507,2015-2019,total,Vivax+Falciparum,0,0.000000
13895,MT,Mato Grosso,Vila Rica,5108600,2015-2019,total,Vivax+Falciparum,0,0.000000

In [4]:
malaria_df.to_excel('malaria_dataset.xlsx', index=False)

Buscando o estado com maior número de casos totais:

In [5]:
periodos_desejados = ['2004-2008', '2015-2019']
filtros = (epidem_indic['disease'].isin(malaria)) & (epidem_indic['period'].isin(periodos_desejados))
dados_filtrados = epidem_indic[filtros]

# Agrupa os dados por estado e soma os casos
soma_casos_por_estado = dados_filtrados.groupby('state')['cases'].sum()

# Ordena os estados em ordem decrescente de casos
soma_casos_por_estado = soma_casos_por_estado.sort_values(ascending=False)

# Obtém o estado com o maior número de casos
estado_maior_casos = soma_casos_por_estado.index[0]

#############################

# Agrupa os dados por estado e período

soma_casos_por_estado_periodo = dados_filtrados.groupby(['state', 'period'])['cases'].sum()

soma_casos_por_estado_periodo = soma_casos_por_estado_periodo.sort_values(ascending=False)

estado_periodo_maior_casos = soma_casos_por_estado_periodo.index[0]


# Exibe o estado com o maior índice de casos
print(soma_casos_por_estado)
print(' ')
print("Estado com maior índice de casos:", estado_maior_casos)

state
Amazonas       2942448
Pará           1531723
Rondônia       1285857
Acre            935609
Roraima         420351
Amapá           419318
Maranhão        127282
Mato Grosso      82837
Tocantins         5494
Name: cases, dtype: int64

Estado com maior índice de casos: Amazonas

Buscando o estado com maior número de casos por período:

In [6]:
# Exibe o estado com o maior índice de casos
print(soma_casos_por_estado_periodo)
print(' ')
print("Estado com maior índice de casos:", estado_periodo_maior_casos)

state        period
Amazonas     2004-2008    2149875
Rondônia     2004-2008    1184044
Pará         2004-2008    1169876
Amazonas     2015-2019     792573
Acre         2004-2008     621070
Pará         2015-2019     361847
Acre         2015-2019     314539
Amapá        2004-2008     266271
Roraima      2004-2008     243696
             2015-2019     176655
Amapá        2015-2019     153047
Maranhão     2004-2008     117171
Rondônia     2015-2019     101813
Mato Grosso  2004-2008      71132
             2015-2019      11705
Maranhão     2015-2019      10111
Tocantins    2004-2008       5141
             2015-2019        353
Name: cases, dtype: int64

Estado com maior índice de casos: ('Amazonas', '2004-2008')

In [7]:
# Filtra os dados para o período de 2004-2008
dados_2004_2008 = dados_filtrados[dados_filtrados['period'] == '2004-2008']

# Agrupa os dados por estado e soma os casos para o período
soma_casos_2004_2008 = dados_2004_2008.groupby('state')['cases'].sum()

# Ordena os estados em ordem decrescente de casos para o período
soma_casos_2004_2008 = soma_casos_2004_2008.sort_values(ascending=False)

# Obtém o estado com o maior número de casos para o período
estado_maior_casos_2004_2008 = soma_casos_2004_2008.index[0]

###############

dados_2015_2019 = dados_filtrados[dados_filtrados['period'] == '2015-2019']

soma_casos_2015_2019 = dados_2015_2019.groupby('state')['cases'].sum()

soma_casos_2015_2019 = soma_casos_2015_2019.sort_values(ascending=False)

estado_maior_casos_2015_2019 = soma_casos_2015_2019.index[0]

In [8]:
# Exibe os estados com o maior índice de casos para cada período
print("Período de 2004-2008:")
print(soma_casos_2004_2008)
print("Estado com maior índice de casos no período de 2004-2008:", estado_maior_casos_2004_2008)

print(' ')

print("Período de 2015-2019:")
print(soma_casos_2015_2019)
print("Estado com maior índice de casos no período de 2015-2019:", estado_maior_casos_2015_2019)

Período de 2004-2008:
state
Amazonas       2149875
Rondônia       1184044
Pará           1169876
Acre            621070
Amapá           266271
Roraima         243696
Maranhão        117171
Mato Grosso      71132
Tocantins         5141
Name: cases, dtype: int64
Estado com maior índice de casos no período de 2004-2008: Amazonas

Período de 2015-2019:
state
Amazonas       792573
Pará           361847
Acre           314539
Roraima        176655
Amapá          153047
Rondônia       101813
Mato Grosso     11705
Maranhão        10111
Tocantins         353
Name: cases, dtype: int64
Estado com maior índice de casos no período de 2015-2019: Amazonas

Buscando qual tipo de protozoário $Plasmodium$ causou mais infecções:

In [9]:
periodos_desejados = ['2004-2008', '2015-2019']
filtros = (epidem_indic['disease'].isin(malaria)) & (epidem_indic['period'].isin(periodos_desejados))
dados_filtrados = epidem_indic[filtros]

# Agrupa os dados por estado e soma os casos
soma_casos_por_especie = dados_filtrados.groupby('disease')['cases'].sum()

# Ordena os estados em ordem decrescente de casos
soma_casos_por_especie = soma_casos_por_especie.sort_values(ascending=False)

# Obtém o estado com o maior número de casos
especie_maior_casos = soma_casos_por_especie.index[0]

#############################

# Agrupa os dados por estado e período

soma_casos_por_especie_periodo = dados_filtrados.groupby(['disease', 'period'])['cases'].sum()

soma_casos_por_especie_periodo = soma_casos_por_especie_periodo.sort_values(ascending=False)

especie_periodo_maior_casos = soma_casos_por_especie_periodo.index[0]


# Exibe o estado com o maior índice de casos
print(soma_casos_por_especie)
print(' ')
print("Espécie com maior índice de casos:", especie_maior_casos)

disease
Vivax               6175008
Falciparum          1522261
Vivax+Falciparum      53776
Name: cases, dtype: int64

Espécie com maior índice de casos: Vivax

Buscando qual tipo de protozoário $Plasmodium$ causou mais infecções por período:

In [10]:
# Filtra os dados para o período de 2004-2008
dados_2004_2008 = dados_filtrados[dados_filtrados['period'] == '2004-2008']

# Agrupa os dados por estado e soma os casos para o período
soma_casos_2004_2008 = dados_2004_2008.groupby('disease')['cases'].sum()

# Ordena os estados em ordem decrescente de casos para o período
soma_casos_2004_2008 = soma_casos_2004_2008.sort_values(ascending=False)

# Obtém o estado com o maior número de casos para o período
especie_maior_casos_2004_2008 = soma_casos_2004_2008.index[0]

###############

dados_2015_2019 = dados_filtrados[dados_filtrados['period'] == '2015-2019']

soma_casos_2015_2019 = dados_2015_2019.groupby('disease')['cases'].sum()

soma_casos_2015_2019 = soma_casos_2015_2019.sort_values(ascending=False)

especie_maior_casos_2015_2019 = soma_casos_2015_2019.index[0]

In [11]:
# Exibe as cidades com o maior índice de casos para cada período
print("Período de 2004-2008:")
print(soma_casos_2004_2008)
print("Espécie com maior índice de casos no período de 2004-2008:", especie_maior_casos_2004_2008)

print(' ')

print("Período de 2015-2019:")
print(soma_casos_2015_2019)
print("Espécie com maior índice de casos no período de 2015-2019:", especie_maior_casos_2015_2019)

Período de 2004-2008:
disease
Vivax               4429775
Falciparum          1350721
Vivax+Falciparum      47780
Name: cases, dtype: int64
Espécie com maior índice de casos no período de 2004-2008: Vivax

Período de 2015-2019:
disease
Vivax               1745233
Falciparum           171540
Vivax+Falciparum       5996
Name: cases, dtype: int64
Espécie com maior índice de casos no período de 2015-2019: Vivax

Filtrando dados do estado do Amazonas:

In [12]:
# Define os valores desejados
amazonas = ['Amazonas']

# Filtra as linhas com os valores desejados na coluna 'state'
amazonas_df = epidem_indic[epidem_indic['state'].isin(amazonas)]

# Exibe as linhas filtradas
amazonas_df = amazonas_df.reset_index()
amazonas_df = amazonas_df.drop(['index'], axis=1)
amazonas_df

,state_abbrev,state,municipality,geocode,period,zone,disease,cases,inc
0,AM,Amazonas,Alvarães,1300029,2004-2008,rural,chagas,0,0.000000
1,AM,Amazonas,Amaturá,1300060,2004-2008,rural,chagas,0,0.000000
2,AM,Amazonas,Anamã,1300086,2004-2008,rural,chagas,1,4.867059
3,AM,Amazonas,Anori,1300102,2004-2008,rural,chagas,0,0.000000
4,AM,Amazonas,Apuí,1300144,2004-2008,rural,chagas,0,0.000000
...,...,...,...,...,...,...,...,...,...
2599,AM,Amazonas,Tefé,1304203,2015-2019,total,Vivax+Falciparum,13,4.192128
2600,AM,Amazonas,Tonantins,1304237,2015-2019,total,Vivax+Falciparum,2,2.129699
2601,AM,Amazonas,Uarini,1304260,2015-2019,total,Vivax+Falciparum,0,0.000000
2602,AM,Amazonas,Urucará,1304302,2015-2019,total,Vivax+Falciparum,0,0.000000
2603,AM,Amazonas,Urucurituba,1304401,2015-2019,total,Vivax+Falciparum,0,0.000000

Filtrando dados de malária no estado do Amazonas:

In [13]:
# Combina os DataFrames malaria_df e amazonas_df com base nas colunas desejadas
combined_df = amazonas_df.copy()

# Filtra as linhas com os valores desejados na coluna 'disease' no DataFrame amazonas_df
combined_df = combined_df[combined_df['disease'].isin(malaria)]

# Exibe o DataFrame filtrado para o Amazonas
combined_df = combined_df.reset_index(drop=True)
combined_df

,state_abbrev,state,municipality,geocode,period,zone,disease,cases,inc
0,AM,Amazonas,Alvarães,1300029,2004-2008,rural,Falciparum,3448,10602.980971
1,AM,Amazonas,Amaturá,1300060,2004-2008,rural,Falciparum,23,105.599426
2,AM,Amazonas,Anamã,1300086,2004-2008,rural,Falciparum,342,1664.534132
3,AM,Amazonas,Anori,1300102,2004-2008,rural,Falciparum,80,318.156110
4,AM,Amazonas,Apuí,1300144,2004-2008,rural,Falciparum,1016,2506.661692
...,...,...,...,...,...,...,...,...,...
1111,AM,Amazonas,Tefé,1304203,2015-2019,total,Vivax+Falciparum,13,4.192128
1112,AM,Amazonas,Tonantins,1304237,2015-2019,total,Vivax+Falciparum,2,2.129699
1113,AM,Amazonas,Uarini,1304260,2015-2019,total,Vivax+Falciparum,0,0.000000
1114,AM,Amazonas,Urucará,1304302,2015-2019,total,Vivax+Falciparum,0,0.000000
1115,AM,Amazonas,Urucurituba,1304401,2015-2019,total,Vivax+Falciparum,0,0.000000

Buscando o município com maior número de casos:

In [14]:
filtros = (epidem_indic['disease'].isin(malaria)) & (epidem_indic['period'].isin(periodos_desejados)) & (epidem_indic['state'].isin(amazonas))
dados_filtrados = epidem_indic[filtros]

# Agrupa os dados por estado e soma os casos
soma_casos_por_cidade = dados_filtrados.groupby('municipality')['cases'].sum()

# Ordena os estados em ordem decrescente de casos
soma_casos_por_cidade = soma_casos_por_cidade.sort_values(ascending=False)

# Obtém o estado com o maior número de casos
cidade_maior_casos = soma_casos_por_cidade.index[0]

#############################

# Agrupa os dados por estado e período

soma_casos_por_cidade_periodo = dados_filtrados.groupby(['municipality', 'period'])['cases'].sum()

soma_casos_por_cidade_periodo = soma_casos_por_cidade_periodo.sort_values(ascending=False)

cidade_periodo_maior_casos = soma_casos_por_cidade_periodo.index[0]


# Exibe o estado com o maior índice de casos
print(soma_casos_por_cidade)
print(' ')
print("Cidade com maior índice de casos:", cidade_maior_casos)

municipality
Manaus                      786128
São Gabriel da Cachoeira    158140
Barcelos                    122514
Coari                       112852
Careiro                     105518
                             ...
Tonantins                     1088
Amaturá                        604
Urucurituba                    229
Barreirinha                    201
Boa Vista do Ramos             172
Name: cases, Length: 62, dtype: int64

Cidade com maior índice de casos: Manaus

Buscando o município com maior número de casos por período:

In [15]:
# Filtra os dados para o período de 2004-2008
dados_2004_2008 = dados_filtrados[dados_filtrados['period'] == '2004-2008']

# Agrupa os dados por estado e soma os casos para o período
soma_casos_2004_2008 = dados_2004_2008.groupby('municipality')['cases'].sum()

# Ordena os estados em ordem decrescente de casos para o período
soma_casos_2004_2008 = soma_casos_2004_2008.sort_values(ascending=False)

# Obtém o estado com o maior número de casos para o período
cidade_maior_casos_2004_2008 = soma_casos_2004_2008.index[0]

###############

dados_2015_2019 = dados_filtrados[dados_filtrados['period'] == '2015-2019']

soma_casos_2015_2019 = dados_2015_2019.groupby('municipality')['cases'].sum()

soma_casos_2015_2019 = soma_casos_2015_2019.sort_values(ascending=False)

cidade_maior_casos_2015_2019 = soma_casos_2015_2019.index[0]

In [16]:
# Exibe as cidades com o maior índice de casos para cada período
print("Período de 2004-2008:")
print(soma_casos_2004_2008)
print("Cidade com maior índice de casos no período de 2004-2008:", cidade_maior_casos_2004_2008)

print(' ')

print("Período de 2015-2019:")
print(soma_casos_2015_2019)
print("Cidade com maior índice de casos no período de 2015-2019:", cidade_maior_casos_2015_2019)

Período de 2004-2008:
municipality
Manaus                660604
Careiro               101770
Manacapuru             81632
Coari                  80324
Tefé                   74280
                       ...
Amaturá                  422
Envira                   217
Urucurituba              182
Barreirinha              114
Boa Vista do Ramos        74
Name: cases, Length: 62, dtype: int64
Cidade com maior índice de casos no período de 2004-2008: Manaus

Período de 2015-2019:
municipality
Manaus                       125524
São Gabriel da Cachoeira     117994
Barcelos                      67246
Santa Isabel do Rio Negro     43372
Lábrea                        36544
                              ...
Anamã                            99
Boa Vista do Ramos               98
Barreirinha                      87
Urucurituba                      47
Anori                            28
Name: cases, Length: 62, dtype: int64
Cidade com maior índice de casos no período de 2015-2019: Manaus

In [17]:
municipio_max = ['Manaus']

# Filtra as linhas com os valores desejados na coluna 'disease' no DataFrame amazonas_df
combined_df = combined_df[combined_df['municipality'].isin(municipio_max)]

# Exibe o DataFrame filtrado para o Amazonas
combined_df = combined_df.reset_index(drop=True)
combined_df

,state_abbrev,state,municipality,geocode,period,zone,disease,cases,inc
0,AM,Amazonas,Manaus,1302603,2004-2008,rural,Falciparum,22273,52053.049549
1,AM,Amazonas,Manaus,1302603,2015-2019,rural,Falciparum,78,182.289672
2,AM,Amazonas,Manaus,1302603,2004-2008,urban,Falciparum,44105,525.070090
3,AM,Amazonas,Manaus,1302603,2015-2019,urban,Falciparum,398,4.738191
4,AM,Amazonas,Manaus,1302603,2004-2008,total,Falciparum,66378,786.225129
5,AM,Amazonas,Manaus,1302603,2015-2019,total,Falciparum,476,4.468930
6,AM,Amazonas,Manaus,1302603,2004-2008,rural,Vivax,78745,184030.772087
7,AM,Amazonas,Manaus,1302603,2015-2019,rural,Vivax,25859,60433.700367
8,AM,Amazonas,Manaus,1302603,2004-2008,urban,Vivax,183519,2184.793966
9,AM,Amazonas,Manaus,1302603,2015-2019,urban,Vivax,36387,433.187289
10,AM,Amazonas,Manaus,1302603,2004-2008,total,Vivax,262264,3106.429047
11,AM,Amazonas,Manaus,1302603,2015-2019,total,Vivax,62246,584.397051
12,AM,Amazonas,Manaus,1302603,2004-2008,rural,Vivax+Falciparum,433,1011.941384
13,AM,Amazonas,Manaus,1302603,2015-2019,rural,Vivax+Falciparum,8,18.696377
14,AM,Amazonas,Manaus,1302603,2004-2008,urban,Vivax+Falciparum,1227,14.607437
15,AM,Amazonas,Manaus,1302603,2015-2019,urban,Vivax+Falciparum,32,0.380960
16,AM,Amazonas,Manaus,1302603,2004-2008,total,Vivax+Falciparum,1660,19.662143
17,AM,Amazonas,Manaus,1302603,2015-2019,total,Vivax+Falciparum,40,0.375540

In [18]:
# Filtra os dados para o período de 2004-2008
dados_2004_2008 = dados_filtrados[dados_filtrados['period'] == '2004-2008']

# Agrupa os dados por estado e soma os casos para o período
soma_casos_2004_2008 = dados_2004_2008.groupby(['disease', 'municipality'])['cases'].sum()

# Ordena os estados em ordem decrescente de casos para o período
soma_casos_2004_2008 = soma_casos_2004_2008.sort_values(ascending=False)

# Obtém o estado com o maior número de casos para o período
especie_maior_casos_2004_2008 = soma_casos_2004_2008.index[0]

###############

dados_2015_2019 = dados_filtrados[dados_filtrados['period'] == '2015-2019']

soma_casos_2015_2019 = dados_2015_2019.groupby(['disease', 'municipality'])['cases'].sum()

soma_casos_2015_2019 = soma_casos_2015_2019.sort_values(ascending=False)

especie_maior_casos_2015_2019 = soma_casos_2015_2019.index[0]

In [19]:
# Exibe as cidades com o maior índice de casos para cada período
print("Período de 2004-2008:")
print(soma_casos_2004_2008)
print("Espécie com maior índice de casos no período de 2004-2008:", especie_maior_casos_2004_2008)

print(' ')

print("Período de 2015-2019:")
print(soma_casos_2015_2019)
print("Espécie com maior índice de casos no período de 2015-2019:", especie_maior_casos_2015_2019)

Período de 2004-2008:
disease           municipality
Vivax             Manaus                524528
Falciparum        Manaus                132756
Vivax             Careiro                76002
                  Manacapuru             63046
                  Coari                  57906
                                         ...
Vivax+Falciparum  Envira                     1
                  Fonte Boa                  1
                  Eirunepé                   0
                  Boa Vista do Ramos         0
                  Urucurituba                0
Name: cases, Length: 186, dtype: int64
Espécie com maior índice de casos no período de 2004-2008: ('Vivax', 'Manaus')

Período de 2015-2019:
disease           municipality
Vivax             Manaus                      124492
                  São Gabriel da Cachoeira    101304
                  Barcelos                     55134
                  Lábrea                       35134
                  Coari                        32208
                                               ...
Vivax+Falciparum  Iranduba                         0
                  Itacoatiara                      0
                  Itapiranga                       0
                  Manacapuru                       0
                  Urucurituba                      0
Name: cases, Length: 186, dtype: int64
Espécie com maior índice de casos no período de 2015-2019: ('Vivax', 'Manaus')

In [20]:
# Define os períodos desejados
periodos_desejados = ['2004-2008', '2015-2019']

# Loop for para separar as doenças por período
for doenca in malaria:
    for periodo in periodos_desejados:
        for estado in amazonas:
            # Filtra os dados para a doença e período desejados
            dados_filtrados = epidem_indic[(epidem_indic['disease'] == doenca) & (epidem_indic['period'] == periodo) & (epidem_indic['state'] == estado)]

            # Agrupa os dados por município e soma os casos
            soma_casos = dados_filtrados.groupby('municipality')['cases'].sum()

            # Ordena os municípios em ordem decrescente de casos
            soma_casos = soma_casos.sort_values(ascending=False)

            # Obtém o município com o maior número de casos
            municipio_maior_casos = soma_casos.index[0]
    
            # Exibe as informações para a doença e período atual
            print(f"Doença: {doenca}, Período: {periodo}")
            print(soma_casos)
            print("Município com maior índice de casos:", municipio_maior_casos)
            print('\n')

Doença: Falciparum, Período: 2004-2008
municipality
Manaus                132756
Careiro                25364
Coari                  22086
Manacapuru             18482
Tefé                   18284
                       ...
Amaturá                   50
Envira                    32
Urucurituba               30
Boa Vista do Ramos        10
Barreirinha               10
Name: cases, Length: 62, dtype: int64
Município com maior índice de casos: Manaus


Doença: Falciparum, Período: 2015-2019
municipality
São Gabriel da Cachoeira     15748
Barcelos                     11444
Santa Isabel do Rio Negro    11078
Guajará                       3750
Atalaia do Norte              3666
                             ...
Autazes                          0
São Sebastião do Uatumã          0
Manaquiri                        0
Anori                            0
Careiro da Várzea                0
Name: cases, Length: 62, dtype: int64
Município com maior índice de casos: São Gabriel da Cachoeira


Doença: Vivax, Período: 2004-2008
municipality
Manaus                524528
Careiro                76002
Manacapuru             63046
Coari                  57906
Tefé                   55882
                       ...
Amaturá                  368
Envira                   184
Urucurituba              152
Barreirinha               92
Boa Vista do Ramos        64
Name: cases, Length: 62, dtype: int64
Município com maior índice de casos: Manaus


Doença: Vivax, Período: 2015-2019
municipality
Manaus                      124492
São Gabriel da Cachoeira    101304
Barcelos                     55134
Lábrea                       35134
Coari                        32208
                             ...
Boa Vista do Ramos              98
Anamã                           98
Barreirinha                     82
Urucurituba                     46
Anori                           28
Name: cases, Length: 62, dtype: int64
Município com maior índice de casos: Manaus


Doença: Vivax+Falciparum, Período: 2004-2008
municipality
Manaus                     3320
São Sebastião do Uatumã    1846
Lábrea                     1570
Barcelos                    928
Urucará                     922
                           ...
Fonte Boa                     1
Envira                        1
Eirunepé                      0
Boa Vista do Ramos            0
Urucurituba                   0
Name: cases, Length: 62, dtype: int64
Município com maior índice de casos: Manaus


Doença: Vivax+Falciparum, Período: 2015-2019
municipality
São Gabriel da Cachoeira     942
Santa Isabel do Rio Negro    856
Barcelos                     668
Atalaia do Norte             114
Manaus                        80
                            ...
Iranduba                       0
Careiro                        0
Careiro da Várzea              0
Fonte Boa                      0
Urucurituba                    0
Name: cases, Length: 62, dtype: int64
Município com maior índice de casos: São Gabriel da Cachoeira